### ISSUE TITLE
Suspected incorrect copyright assertion

### ISSUE THREAD

**Issue by pmonks** [symphonyoss/symphony-rest-tools#1]
[This line in the NOTICE file](https://github.com/symphonyoss/symphony-rest-tools/blob/master/NOTICE#L2) states that the copyright for this project lies with the Symphony Software Foundation, but I believe copyright is held by Symphony Communication Services LLC.

**Comment by pmonks** [comment]
It looks like a similar problem exists in the header comments of the source files too.

**Comment by bruceskingle** [comment]
Fixed
